### PR TITLE
Listen on all interfaces

### PR DESCRIPTION
**Pull request by sigmaSd**
Listen on all interfaces with the added bonus of fixing it on windows. (https://github.com/ebfull/pcap/issues/53)

### CODE REVIEW

**Comment by sigmaSd** [comment]
Actually it looks like the issue is fixed in master https://github.com/ebfull/pcap/commit/8c4fed5c7c296b5ff01516ada31ce2b7052887bf

So no need for this anymore

**Comment by DefunctLizard** [comment]
Great, so does it work on windows?

**Comment by sigmaSd** [comment]
Not quite unfortanatly, now I'm running into another bug https://github.com/ebfull/pcap/issues/150 maybe the maintainer will figure it out

**Comment by sigmaSd** [comment]
Well it runs now (running cmd in admin mode) but Its not detecting any ip, I'll see if I can debug it.

**Comment by sigmaSd** [comment]
On windows Device::loopkup() picks the wrong device unfortanatly

**Comment by DefunctLizard** [comment]
Maybe we can look up all the devices and ask the user for the correct one?

**Comment by sigmaSd** [comment]
Yes that will be an acceptable workaround

**Pull request closed without merging**
