### PR TITLE
Add ci

### PR DESCRIPTION
**Pull request by sigmaSd**
This pr add automatic releases by github actions.
steps:
-  add tag: git tag -a x.x.x
-  push the new tag: git push --follow-tags or git push origin x.x.x

I stubbed the use name in windows, this can be easily added later.(with winapi)

### CODE REVIEW

**Comment by sigmaSd** [comment]
I only noticed what you're using the users crate for when I tested it on windows xD

So I removed the root check for windows for now

**Comment by DefunctLizard** [comment]
Looks great! Merging it now.

**Comment by sigmaSd** [comment]
I tested it on windows , I run into https://github.com/ebfull/pcap/issues/53

Using Device::list actually works though!

**Comment by DefunctLizard** [comment]
Sure, just do whatever you can to make it work and I will pull it in.

**Comment by sigmaSd** [comment]
The problem is selecting the interface

You can do
```rust
Device::list().into_iter().for_each(|d|{thread::spawn(|| loop{handle_packet()})
```
This will make it that it listen on all intetfaces and at the same time will fix it in windows

**Comment by DefunctLizard** [comment]
I'll make a branch to test that.

**Pull request merged**
